### ISSUE TITLE
Double slash inside of string being detected as comment

### ISSUE THREAD

**Issue by zanysoft** [tedious/JShrink#102] opened 2021-01-11 12:58 UTC
In code i returning a url "https://player.vimeo.com/api/player.js"

`getApiURL(){return "https://player.vimeo.com/api/player.js"}}`

 but after minifying code is removed after "https:" because you code consider a url as comment after double slash.
code after minified:
`getApiURL(){return "https:;`

**Comment by hellokoda** [comment] 2023-02-04 10:36
It seems this is no longer an issue but I might be wrong, here was my implementation and results from using code you had supplied.

Ignore the $scripts->get stuff, this was my usage, for the page I tested it on, I used your code 

```php
$scriptContent = Minifier::minify($scripts->get($page->scripts, [
     "global_access" => false,
     "cross_var" => true
]), array('flaggedComments' => false));
```

Code in JavaScript: 
```js
var test = {getApiURL(){return "https://player.vimeo.com/api/player.js"}};
console.log(test.getApiURL());
```

I was able to get the issues code without issues.
```json
{
    "pageHtml": "<h1>test script stuff</h1>",
    "script": ["var test={getApiURL(){return\"https:\/\/player.vimeo.com\/api\/player.js\"}}\nconsole.log(test.getApiURL())"]
}
```

The code was executed and came out like such:
![image](https://user-images.githubusercontent.com/46235562/216762278-5669e52f-f614-48a4-a5e0-7c8bec5daa46.png)

**Comment by hellokoda** [comment] 2023-02-04 10:37
Oh boy I'm an idiot, I glanced at the date and thought it was Jan 11, 2023 and not 2021 🤦‍♂️

**Comment by tedivm** [comment] 2023-03-06 00:02
I can't reproduce this so I'm closing it, but if you can come up with a test case with the current version of jshrink please let me know!

**Closed** 2023-03-06 00:02 UTC
Labels: Priority: High, Status: Accepted, Type: Bug
