### ISSUE TITLE
Some js not usable after JShrink minification (example: axios code)

### ISSUE THREAD

**Issue by peminator** [tedious/JShrink#107] opened 2022-05-04 12:01 UTC
I tried to put into one .js file to minify count of file requests, first content of minified axios javascript, then some newline (comments etc) and then own code.

Axios is sure a modern and popular thing which should be considered important,
and if it minified is buggy, then possibly other llibraries using the same minification may cause the same issues
(webpack based minification)

Without shrinking it works fine, minified code from JSrink does not work anymore

To repeat, just find axios cdn, try copypasting content to local js file, then add newline and some own simple command, like 

```
/* axios minified code first*/
{put here contents from https://cdnjs.cloudflare.com/ajax/libs/axios/0.27.2/axios.min.js}

/* own code */
console.log(1234);
document.body.innerHTML = 'WORKS!';

```

then just use script tag in some html, and after loading check console

**Comment by GaryHeaven** [comment] 2022-09-26 08:35
A better case is (from extensions-leaflet-map, php7.4 or 8.x) 
`if ((a._map != null && a._map._leaflet_id == map_id) ||
				 	a._map == null ) {`
minifies to 
`if(((a._map!=null)&#038;&#038;(a._map._leaflet_id==map_id))||a._map==null){`

**Comment by tedivm** [comment] 2023-03-04 18:51
Closing as duplicate of #101

**Closed by tedivm** 2023-03-04 18:51 UTC
