### ISSUE TITLE
Error in handling of /^(?:[a-z]+:)?\/\//

### ISSUE THREAD

**Issue by ThomasDaheim** [tedious/JShrink#95] opened 2020-11-11 15:12 UTC
I have tried to use JShrink v1.3.3 on pannellum.js (from https://github.com/mpetroff/pannellum/releases/download/2.5.6/pannellum-2.5.6.zip) and I have found the following:

pannellum.js contains `/^(?:[a-z]+:)?\/\//` which can't be handled by JShrink. What happens: Everything after `\/\` is skipped until the end of the current line.

Any hints on how to avoid/resolve this are welcome!

**Comment by tedivm** [comment] 2023-03-04 18:54
Closing as duplicate of #101

**Closed** 2023-03-04 18:56 UTC
