### ISSUE TITLE
Unclosed regex pattern at position: 374544

### ISSUE THREAD

**Issue by djokodonev** [tedious/JShrink#39] opened 2014-10-29 09:53 UTC
I used the shrinker inside a framework we use, and it worked fine at first but now it started failing a lot and it is taking a very long time to do the shrinking i mean minutes.

I suspected the error was comming from somne javascript that had utf8 characters in it since lal string functions are not utf8 compatible. 

I changed the functions(substr, strpos) to (mb_strpos, mb_substr) but this did not help. Any ideas as to what is causing the script to run so slow?

**Comment by tedivm** [comment] 2015-03-09 06:25
This is a duplicate of #13.

**Closed by tedivm** 2015-03-09 06:25 UTC
